### PR TITLE
feat:Added the image upload functionality

### LINKED ISSUE #17: [Add Blog feature] Adding Validation to Image field while posting a blog
Observed an issue while creating a new blog that we can populate any invalid data in the image field. 

As a result the image is not rendered.

image

image

I can work on this.
@ojasaklechayt Can you please assign this issue to me under hacktoberfest .

### PR DESCRIPTION
**Pull request by aasimtaif**
fixes #17 
fixed the issue of Adding Validation to the Image field while posting a blog by changing image uri upload ti image upload and the image then gets converted into base64 format 
And changed the witdh of form
Screenshot from 2023-10-22 18-01-37
 
Screenshot from 2023-10-22 18-03-26

As you can see the image upload is working properly

### CODE REVIEW

**Comment by ojasaklechayt** [comment]
@aasimtaif We are having this issue - 

image

Can you please check once, there was some merge conflict which I tried to solve and it gave me this error

**Comment by aasimtaif** [comment]
> @aasimtaif We are having this issue -
> 
> image
> 
> Can you please check once, there was some merge conflict which I tried to solve and it gave me this error

I think this is happening due to your  latest merge of another PR of this issue 
If you want the image upload option then you don't need the verification part

**Comment by aasimtaif** [comment]
thank you so much

**Comment by ojasaklechayt** [comment]
@aasimtaif please check #28

**Pull request merged**
